CREATE TABLE ANO(
	IDANO INT PRIMARY KEY IDENTITY,
	ANO DATE 
)

CREATE TABLE MES(
	IDMES INT PRIMARY KEY IDENTITY,
	MES DATE
)

CREATE TABLE FABRICANTE(
	IDFABRICANTE INT PRIMARY KEY IDENTITY,
	NOME VARCHAR (50), 
	CIDADE VARCHAR (15),
	UF VARCHAR,
	IDENDERECO INT 
	CONSTRAINT FK_IDENDERECO FOREIGN KEY REFERENCES ENDERECO (IDENDERECO),
	TELEFONE VARCHAR(15),
	CONTATO VARCHAR(15)
)

CREATE TABLE MODELO(
	IDMODELO INT PRIMARY KEY IDENTITY,
	DESCRICAO VARCHAR (200)
)

CREATE TABLE VEICULO(
	IDVEICULO INT PRIMARY KEY IDENTITY,
	DESCRICAO VARCHAR (255), 
	VALOR MONEY,
	IDMODELO INT 
	CONSTRAINT FK_IDMODELO FOREIGN KEY REFERENCES MODELO (IDMODELO),
	IDFABRICANTE INT 
	CONSTRAINT FK_IDFABRICANTE FOREIGN KEY REFERENCES FABRICANTE (IDFABRICANTE),
	IDANOFABRICACAO INT 
	CONSTRAINT FK_IDANOFABRICACAO FOREIGN KEY REFERENCES ANO (IDANO)
)

CREATE TABLE VENDASANUAIS(
	IDVENDAS INT PRIMARY KEY IDENTITY,
	QTD INT, 
	IDVEICULO INT 
	CONSTRAINT FK_IDVEICULO FOREIGN KEY REFERENCES VEICULO (IDVEICULO),
	IDANODAVENDA INT 
	CONSTRAINT FK_IDANODAVENDA FOREIGN KEY REFERENCES ANO (IDANO),
	IDMESDAVENDA INT 
	CONSTRAINT FK_IDMESDAVENDA FOREIGN KEY REFERENCES MES (IDMES)
)

--CRIANDO A TABELA ENDEREÇO E A TABELA ASSOCIATIVA
CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY IDENTITY,
	LOGRADOURO VARCHAR(20),
	NUMERO INT,
	COMPLEMENTO VARCHAR(30)
)

CREATE TABLE ENDERECO_FABRICANTE(	
	IDENDERECO_FABRICANTE INT PRIMARY KEY IDENTITY,
	IDENDERECO INT 
	CONSTRAINT FK_IDENDERECO FOREIGN KEY REFERENCES ENDERECO (IDENDERECO),
	IDFABRICANTE INT 
	CONSTRAINT FK_IDFABRICANTE FOREIGN KEY REFERENCES FABRICANTE (IDFABRICANTE)
)

--REALIZANDO AS ALTERAÇÕES NAS TABELAS
ALTER TABLE VENDASANUAIS
ADD CONSTRAINT PK_IDVENDAS PRIMARY KEY (IDVENDAS, IDVEICULO, IDANODAVENDA, IDMESDAVENDA)

ALTER TABLE FABRICANTES DROP COLUMN ENDERECO
 
ALTER TABLE FABRICANTES
ADD CONSTRAINT FK_IDENDERECO FOREIGN KEY (ENDERECO) REFERENCES ENDERECO(IDENDERECO) 

ALTER TABLE FABRICANTES
ALTER COLUMN CONTATO SET DEFAULT 'N/D';

ALTER TABLE MES
ADD CONSTRAINT CHK_MES CHECK (MES > 0 AND MES < 13)

ALTER TABLE MES
ALTER COLUMN MES INT UNIQUE

ALTER TABLE ANO
ALTER COLUMN ANO INT UNIQUE

ALTER TABLE ANO
ADD CONSTRAINT CHK_ANO CHECK (ANO >= 1970)

--TESTES
SELECT
	E.LOGRADOURO,
	E.NUMERO,
	E.COMPLEMENTO,
	F.NOME,
	F.CIDADE,
	F.UF,
	F.TELEFONE,
	F.CONTATO	
FROM
	ENDERECO_FABRICANTE EF
INNER JOIN
	ENDERECO E ON E.IDENDERECO = EF.IDENDERECO
INNER JOIN
	FABRICANTE F ON F.IDFABRICANTE = EF.IDENDERECO_FABRICANTE

)